In [ ]:
import numpy as np
import matplotlib.pyplot as plt
plt.plot(np.random.randn(50).cumsum())
plt.savefig("test1.png")


In [ ]:
import re
#https://docs.python.org/3/library/re.html
states = [' Alabama ', 'Georgia!', 'Georgia', 'georgia', 'FlOrIda','south carolina##', 'West virginia?']
def clean_strings(strings):
    result = []
    for value in strings:
        #removes white space
        value=value.strip()
        value=re.sub('[!#?]','',value)
        value=value.title()
        result.append(value)
    return result

clean_strings(states)

In [ ]:
def remove_punctuation(value):
    #return re.sub('or|[ab]','',value,flags=re.I)
    return re.sub('[?!#]','',value,flags=re.I)

clean_ops=[str.strip,remove_punctuation,str.title]
def clean_strings(strings, ops):
    result=[]
    #value below is a string and strings is the list of strings
    for value in strings:
        for function in ops:
            value=function(value)
        result.append(value)
    return result

clean_strings(states,clean_ops)

In [ ]:
y=[x for x in map(remove_punctuation,states)]
[z for z in map(str.title,y)]

In [ ]:
#generators
def squares(n=10):
    print('Generating squares from 1 to {0}'.format(n**2))
    for i in range(1,n+1):
        print(i)
        yield i**2


In [ ]:
gen=squares(10000)


In [ ]:
for x in gen:
    print(x,end=' ')

In [ ]:
#another even more concise way to use generators is generator expressions
gen = (x ** 2 for x in range(10000000))
#next(gen)
#gen.__next__()
# next(gen)
# next(gen)

In [ ]:
for value in gen:
    if value>100000:
        break
    elif value>1000:
        print(value)
    else:
        pass

In [96]:
#https://docs.python.org/3/library/itertools.html

In [98]:
import itertools
L=[("a",1),("a",2),("b",3),("b",4)]
key_func=lambda x: x[0]

some_dict={}
for key, group in itertools.groupby(L,key_func):
    #print(key + ":",list(group))
    some_dict[key]=list(group)

some_dict

{'a': [('a', 1), ('a', 2)], 'b': [('b', 3), ('b', 4)]}

In [99]:
# example of iterators
type(some_dict)

dict

In [103]:
dict_iterator=iter(some_dict)
type(dict_iterator)
next(dict_iterator)


'a'

In [114]:
import numpy as np
import time
 
t0 = time.perf_counter()
arr1 = np.arange(10000000)
#arr1
t1=time.perf_counter()
t1-t0


0.060025200014933944

In [ ]:
import time
 
t0 = time.perf_counter()
list1= list(range(10000000))
#list1
t1 = time.perf_counter()
t1-t0





1.3898529999423772

In [119]:
%timeit list(range(10000000)) 

1.27 s ± 184 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [ ]:
import numpy as np
#generate some random data
np.random.seed(0)
#data is mean 3 standard deviation 2.5 from a normal distribution, 3 rows, 4 columns
data = 3+2.5*np.random.randn(3,4)
data


array([[7.41013086, 4.00039302, 5.44684496, 8.602233  ],
       [7.66889498, 0.5568053 , 5.37522104, 2.62160698],
       [2.74195287, 4.02649625, 3.36010893, 6.63568377]])

In [118]:
data+data #will now this is add corresponding elements to each other

array([[14.82026173,  8.00078604, 10.89368992, 17.204466  ],
       [15.33778995,  1.1136106 , 10.75044209,  5.24321396],
       [ 5.48390574,  8.05299251,  6.72021786, 13.27136753]])

In [120]:
data.shape

(3, 4)

In [ ]:
#https://numpy.org/devdocs

In [121]:
data.dtype

dtype('float64')

In [130]:
data = 3+2.5*np.arange(15)
arr_int=data.astype(np.int64)
arr_int


array([ 3,  5,  8, 10, 13, 15, 18, 20, 23, 25, 28, 30, 33, 35, 38])

In [131]:
arr_int.dtype

dtype('int64')